### ISSUE TITLE
Suggestion: show 65-70% down the line instead of dead center.

### ISSUE THREAD

**Issue by henryas** [MikeyJL/typewriter-auto-scroll#1]
Hi,

The extension works GREAT. The only problem is that it puts the current line in the dead center of the editor. Sometimes we need to see the code before the current line. I think it is better to put the current line somewhere around 65%-70% of the editor's height.   

Thanks.

Henry

**Comment by laukl** [comment]
Henry,

Great suggestion. I'll take a look tonight!

Mikey

**Comment by laukl** [comment]
@henryas Just made a PR.

1. Command palette: ```Typewriter: Change the offset ...```
2. In your case, I think ```-10``` offset is pretty nice but it's up to you. A negative offset will move the focused line below the vertical centre of you editor and vice versa.

Hope you like it! Let me know if anything plays up.

**Comment by henryas** [comment]
It is perfect. Thanks.
